### ISSUE TITLE
Functionality Checklist

### ISSUE THREAD

**Issue by avarixe** [avarixe/myfifa-mobile#1]
- [ ] Login page
- [ ] Registration page
- [ ] Home page
- [ ] Account page
- [ ] Teams page
  - [ ] Add Team
- [ ] Team page (Dashboard)
  - [ ] Current Date Increment
  - [ ] Edit Team
  - [ ] Remove Team
  - [ ] Contract Expiring List
  - [ ] Injury List
  - [ ] Loan List
  - [ ] Last Match
- [ ] Players page
  - [ ] Add Player
  - [ ] Filters
- [ ] Analytics
  - [ ] Development
    - [ ] Table
    - [ ] Player status filters
    - [ ] OVR/Value toggle
  - [ ] Statistics
    - [ ] Table
    - [ ] Player status filters
    - [ ] Competition, Season filters
    - [ ] Player breakdown by Season + Competition
- [ ] Player page
  - [ ] Player Growth
  - [ ] Player Timeline
    - [ ] Contract
    - [ ] Injury
    - [ ] Transfer
    - [ ] Loan
      - [ ] Activate Transfer 
  - [ ] Edit Player
  - [ ] Retire Player
  - [ ] Release Player
  - [ ] Remove Player
- [ ] Matches page
  - [ ] Add Match
  - [ ] Filters
- [ ] Match page
  - [ ] Edit Match
  - [ ] Remove Match
  - [ ] Match Formation
  - [ ] Match Lineup (mobile)
  - [ ] Match Timeline
    - [ ] Goal
    - [ ] Booking
    - [ ] Substitution
    - [ ] Penalty Shootout
  - [ ] Player Formation
    - [ ] Caps
    - [ ] Lineup OVR
    - [ ] Apply Squad
    - [ ] Save Lineup to Squad
  - [ ] Previous/Next Match link
- [ ] Competitions page
  - [ ] New Competition
- [ ] Competition page
  - [ ] Edit Competition
  - [ ] Remove Competition
  - [ ] Close Competition
  - [ ] Table Stages
  - [ ] Knockout Stages
  - [ ] Highlight champion and team
- [ ] Squads page
  - [ ] Mobile View
  - [ ] Add Squad
  - [ ] Update Squad
  - [ ] Remove Squad
  - [ ] Squad OVR
- [ ] Season page
  - [ ] Value/OVR change
  - [ ] Transfer History
